class Destination {
  String imageUrl; //รูปสถานที่
  String locationName; //ชื่อสถานที่
  String locationaddress; //ที่อยู่สถานที่
  String description; //คำอธิบายสถานที่โดยย่อ
  String howtotravel; //วิธีเดินทางไป

  Destination({
    required this.imageUrl,
    required this.locationName,
    required this.locationaddress,
    required this.description,
    required this.howtotravel,
  });
}

Map<String, String> connectPic = {
  'Taxi บริการที่หน้าสถานี': 'assets/images/taxi.png',
  'สายสีนำ้เงิน สถานีบางซื่อ': 'assets/images/mrtblueline.png',
  'สายสีแดงเข้ม สถานีกรุงเทพอภิวัฒน์': 'assets/images/darkredline.png',
  'สายสีแดงอ่อน สถานีกรุงเทพอภิวัฒน์': 'assets/images/lightredline.png',
  'รถสี่ล้อแดง ผู้โดยสารเลือกปลายทางได้': 'assets/images/bus.png'
};

Map<String, String> comfortPic = {
  'จำหน่ายตั๋วล่วงหน้า': 'assets/images/ticket.png',
  'จำหน่ายตั๋วประจำวัน': 'assets/images/ticket.png',
  'ห้องนำ้สะอาด': 'assets/images/toliet.png',
  'ห้องนำ้ผู้พิการ': 'assets/images/handicaptoliet.png',
};

class StationList {
  String name;
  String postition;
  List<Destination> places;
  List<String> connects;
  List<String> comforts;
  List<String> lines;
  StationList({
    required this.name,
    required this.postition,
    required this.places,
    required this.connects,
    required this.comforts,
    required this.lines,
  });
}

List<StationList> stationLists = [
  StationList(
      name: 'กบินทร์บุรี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'กระสัง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'กรุงเทพ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'กรุงเทพอภิวัฒน์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'กันตัง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'กันทรารมย์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'กาญจนบุรี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'การเคหะ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'กุดจิก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'กุมภวาปี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ขอนแก่น',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ขุนตาน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'คลองจันดี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'คลองจาก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'คลองตัน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'คลองต้นไทร',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'คลองนกเล็ก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'คลองบางพระ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'คลองหลวงแพ่ง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'คลองอุดมชลจร',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'คลองแขวงกลั่น',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'คอกควาย',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'คีรีรัฐนิคม',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'จอมทอง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'จักราช',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'จัตุรัส',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'จันเสน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ฉวาง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชลบุรี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชะอวด',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชะอำ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมทางคลองสิบเก้า',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมทางฉะเชิงเทรา',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมทางตลิ่งชัน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมทางถนนจิระ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมทางทุ่งสง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมทางบัวใหญ่',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมทางบางซื่อ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมทางบ้านดารา',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมทางบ้านภาชี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมทางศรีราชา',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมทางหนองปลาดุก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมทางหาดใหญ่',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมทางเขาชีจรรย์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมทางเขาชุมทอง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมทางแก่งคอย',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมพร',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ชุมแสง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ช่องแค',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ซอยวัดลานบุญ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ญาณสังวราราม',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ดอนสีนนท์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ดอนเมือง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ตรอน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ตรัง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ตลาดพลู',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ตลาดลำนารายณ์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ตะพานหิน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ตันหยงมัส',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ทับกฤช',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ทับสะแก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ทุ่งสีทอง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ท่ากิเลน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ท่าฉลอม',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ท่าชนะ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ท่าสัก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ท่าฬ่อ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ท่าเกษม',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ท่าเรือ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ธนบุรี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'นครปฐม',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'นครราชสีมา',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'นครลำปาง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'นครสวรรค์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'นาบอน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'นาสาร',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'น้ำตก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'น้ำพอง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางกระทุ่ม',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางกระบูน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางกระเจ้า',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางน้ำจืด',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางน้ำเปรี้ยว',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางบอน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางบำหรุ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางปะอิน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางพระ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางมูลนาก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางระมาด',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางละมุง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางสะพานน้อย',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางสะพานใหญ่',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางสีคต',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางเตย',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บางโทรัด',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บำเหน็จณรงค์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บุรีรัมย์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านกรูด',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านกลับ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านกาหลง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านขอม',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านฉิมพลี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านชีผ้าขาว',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านดงบัง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านตาคลี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านทับช้าง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านนาขวาง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านนาโคก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านบ่อ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านปากพลี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านปิน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านป่าหวาย',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านพรหมแสง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านพลูตาหลวง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านสร้าง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านส้อง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านหมอ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านหมี่',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านห้วยขวาง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านเหลื่อม',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านแก้ง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านแหลม',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านโป่ง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านใหม่',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'บ้านไผ่',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ประจวบคีรีขันธ์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ประจันตคาม',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ปราจีนบุรี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ปราณบุรี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ปะทิว',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ปัตตานี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ปากช่อง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ปากท่อ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ปากน้ำโพ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ปาดังเบซาร์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ผาเสด็จ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'พญาไท',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'พรมแดน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'พรหมพิราม',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'พระจอมเกล้า',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'พระปรง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'พัทยา',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'พัทยาใต้',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'พัทลุง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'พานทอง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'พิจิตร',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'พิชัย',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'พิษณุโลก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'มวกเหล็ก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'มหาชัย',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'มักกะสัน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'มาบกะเบา',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'มาบอำมฤต',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ยะลา',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'รพ.รามาธิบดี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'รังสิต',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'รางสะแก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'รางโพธิ์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ราชบุรี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ราชปรารภ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ลพบุรี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ละแม',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ลาดกระบัง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ลาดใหญ่',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ลำชี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ลำปลายมาศ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ลำพูน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'วงเวียนใหญ่',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'วังกรด',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'วังก์พง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'วัฒนานคร',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'วัดสิงห์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'วัดไทร',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ศรีสะเกษ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ศาลาธรรมสพน์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ศาลายา',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ศาลาลำดวน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ศิลาอาสน์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ศีขรภูมิ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สระบุรี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สระแก้ว',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สวนนงนุช',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สวรรคโลก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สวี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สะพานถ้ำกระแซ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สะพานแควใหญ่',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สามเสน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สามแยก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สำโรงทาบ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สีคิ้ว',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สุขุมวิท 71',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สุพรรณบุรี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สุราษฎร์ธานี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สุรินทร์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สุไหงโก,ลก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'สูงเนิน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'หนองกวย',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'หนองคาย',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'หนองตม',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'หนองบัวลาย',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'หนองวิวัฒน์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'หนองสัง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'หนองโดน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'หนองโพ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'หลังสวน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'หัวตะเข้',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'หัวหมาก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'หัวหวาย',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'หัวหิน',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ห้วยสามพาด',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ห้วยเดื่อ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ห้วยแถลง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ห้วยโจด',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'อยุธยา',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'อรัญประเทศ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'อุดรธานี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'อุตรดิตถ์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'อุทุมพรพิสัย',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'อุบลราชธานี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'อุรุพงษ์',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'อโศก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'เกาะมหามงคล',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'เขตเมือง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'เขาทอง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'เขาพระบาท',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'เขาสวนกวาง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'เชียงราก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(name: 'เชียงใหม่', postition: '', places: [
    Destination(
        imageUrl: 'assets/images/nongkai.jpg',
        locationName: 'ประตูท่าแพ',
        locationaddress: 'ถนนท่าแพ ตำบลช้างคลาน อำเภอเมือง จังหวัดเชียงใหม่',
        description:
            'ประตูที่ตั้งอยู่ทางทิศตะวันออก และเป็น 1 ใน 5 ประตูเมืองชั้นในของเวียงเชียงใหม่อีกด้วย ซึ่งถือได้ว่าปัจจุบันนี้ ที่นี่เป็นแค่เพียงประตูเมืองเพียงแห่งเดียวที่มีบานประตูนั่นเอง',
        howtotravel:
            'จากสถานีเชียงใหม่ ให้ใช้บริการรถสี่ล้อแดงไปประตูท่าแพได้'),
    Destination(
        imageUrl: 'assets/images/surat.jpg',
        locationName: 'สวนสัตว์เชียงใหม่',
        locationaddress: 'ถนนห้วยแก้ว ตำบลสุเทพ อำเภอเมือง จังหวัดเชียงใหม่',
        description:
            'มีสัตว์อยู่จำนวนมาก เช่น เม่น นกยูง เสือโคร่ง เสือขาว กวาง แรด ฮิปโปเตมัส ช้าง หมี อีเห็น ยีราฟ และยังมีส่วนจัดแสดงหมีแพนด้า ช่วงช่วง และ หลินฮุ่ย ทูตจากประเทศจีนอีกด้วย',
        howtotravel:
            'จากสถานีเชียงใหม่ ให้ใช้บริการรถสี่ล้อแดงไปสวนสัตว์โดยตรง'),
  ], connects: [
    'สายสีนำ้เงิน สถานีบางซื่อ',
    'สายสีแดงเข้ม สถานีกรุงเทพอภิวัฒน์',
    'สายสีแดงอ่อน สถานีกรุงเทพอภิวัฒน์',
    'รถสี่ล้อแดง ผู้โดยสารเลือกปลายทางได้',
    'Taxi บริการที่หน้าสถานี'
  ], comforts: [
    'จำหน่ายตั๋วล่วงหน้า',
    'จำหน่ายตั๋วประจำวัน',
    'ห้องนำ้สะอาด',
    'ห้องนำ้ผู้พิการ'
  ], lines: [
    "สายเหนือ"
  ]),
  StationList(
      name: 'เด่นชัย',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'เนินมะกอก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'เปรง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'เพชรบุรี',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'เมืองคง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'เมืองพล',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'แก่งเสือเต้น',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'แม่กลอง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'แม่เมาะ',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'โคกกรวด',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'โคกกะเทียม',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'โคกมะกอก',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'โนนสะอาด',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'โนนสูง',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'โพธาราม',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'โยทะกา',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
  StationList(
      name: 'ไชยา',
      postition: '',
      places: [],
      connects: [],
      comforts: [],
      lines: []),
];
