class Seating {
  //รายละเอียดขบวน (ที่นั่ง ชนิดรถ รูปรถภายนอกภายใน) แต่ละขบวนอาจมีมากกว่า 2 ชนิดได้
  String imageUrlExterior; //รูปภายนอกรถ
  String imageUrlInterior; //รูปภายในรถ
  String imageUrlSeatchart; //รูปผังที่นั่ง
  String coachname; //ชื่อชนิดรถ
  String description; //คำอธิบายเพิ่มเติม (เช่น ไม่มีบริการอาหาร)
  String imageUrlConvience; //รูป icon ความสะดวก

  Seating({
    required this.imageUrlExterior,
    required this.imageUrlInterior,
    required this.imageUrlSeatchart,
    required this.coachname,
    required this.description,
    required this.imageUrlConvience,
  });
}

class Destination {
  String imageUrl;
  String scenename;
  String betweenstation;

  Destination({
    required this.imageUrl,
    required this.scenename,
    required this.betweenstation,
  });
}

class TrainList {
  //**ข้อมูลมาจากหน้ารายละเอียดของแต่ละขบวน
  String trainNo; //เลขขบวน
  String trainType; //ประเภทขบวน
  String departureStation; //สถานีต้นทาง
  String departureTime;
  String arriveStation; //สถานีปลายทาง
  String arriveTime;
  String line; //สาย
  List<Seating> seats;
  List<Destination> desinations;

  TrainList(
      {required this.trainNo,
      required this.trainType,
      required this.departureStation,
      required this.arriveTime,
      required this.arriveStation,
      required this.departureTime,
      required this.line,
      required this.seats,
      required this.desinations});
}

List<List<TrainList>> trainLists = [
  [
    //รายชื่อสถานีที่ขบวนที่ระบุจอด พร้อมเวลา
    TrainList(
        trainNo: '7',
        trainType: 'ด่วนพิเศษดีเซลราง',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '09:05',
        arriveStation: 'เชียงใหม่',
        arriveTime: '19:30',
        line: 'North',
        seats: [
          Seating(
            //ชนิดที่ 1
            imageUrlExterior: 'assets/images/trainimage/2nddaewoo_Exterior.png',
            imageUrlInterior: 'assets/images/trainimage/2nddaewoo_interior.jpg',
            imageUrlSeatchart: 'assets/images/seatchart/กซขป76.png',
            coachname: 'ชั้น 2 กซขป.76 รถดีเซลรางปรับอากาศ แดวู',
            description: 'มีบริการอาหาร ของว่าง และเครื่องดื่ม',
            imageUrlConvience: 'assets/images/convience/ความสะดวก_กซขป.png',
          ),
          Seating(
            //ชนิดที่ 2
            imageUrlExterior:
                'assets/images/trainimage/2ndsprinter_Exterior.jpg',
            imageUrlInterior:
                'assets/images/trainimage/2ndsprinter_Interior.png',
            imageUrlSeatchart: 'assets/images/seatchart/กซขป76.png',
            coachname: 'ชั้น 2 กซขป.76 รถดีเซลรางปรับอากาศ สปรินเตอร์',
            description: 'มีบริการอาหาร ของว่าง และเครื่องดื่ม',
            imageUrlConvience: 'assets/images/convience/ความสะดวก_กซขป.png',
          ),
        ],
        desinations: [
          Destination(
            //สถานที่ ที่ 1
            imageUrl: 'assets/images/chiangmai.jpg',
            scenename: 'แม่นำ้บางปะกง',
            betweenstation: 'สถานีฉะเชิงเทรา-ดอนสีนนท์',
          ),
          Destination(
            //สถานที่ ที่ 2
            imageUrl: 'assets/images/nongkai.jpg',
            scenename: 'แกรนด์แคนยอนชลบุรี',
            betweenstation: 'สถานีชลบุรี-บางพระ',
          ),
        ]),
    TrainList(
        trainNo: '8',
        trainType: 'ด่วนพิเศษดีเซลราง',
        departureStation: 'เชียงใหม่',
        departureTime: '08:50',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '18:55',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '9',
        trainType: 'ด่วนพิเศษ CNR',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '18:40',
        arriveStation: 'เชียงใหม่',
        arriveTime: '07:15',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '10',
        trainType: 'ด่วนพิเศษ CNR',
        departureStation: 'เชียงใหม่',
        departureTime: '18:00',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '06:50',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '13',
        trainType: 'ด่วนพิเศษ',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '20:05',
        arriveStation: 'เชียงใหม่',
        arriveTime: '08:40',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '14',
        trainType: 'ด่วนพิเศษ',
        departureStation: 'เชียงใหม่',
        departureTime: '17:00',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '06:10',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '51',
        trainType: 'ด่วน',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '22:30',
        arriveStation: 'เชียงใหม่',
        arriveTime: '12:10',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '52',
        trainType: 'ด่วน',
        departureStation: 'เชียงใหม่',
        departureTime: '15:30',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '05:10',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '109',
        trainType: 'เร็ว',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '14:15',
        arriveStation: 'เชียงใหม่',
        arriveTime: '04:05',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '102',
        trainType: 'เร็ว',
        departureStation: 'เชียงใหม่',
        departureTime: '06:30',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '20:25',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '107',
        trainType: 'เร็ว',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '20:45',
        arriveStation: 'เด่นชัย',
        arriveTime: '05:15',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '108',
        trainType: 'เร็ว',
        departureStation: 'เด่นชัย',
        departureTime: '19:05',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '04:30',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '111',
        trainType: 'เร็ว',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '07:30',
        arriveStation: 'เด่นชัย',
        arriveTime: '16:30',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '112',
        trainType: 'เร็ว',
        departureStation: 'เด่นชัย',
        departureTime: '07:30',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '17:20',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '201',
        trainType: 'ธรรมดา',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '09:30',
        arriveStation: 'พิษณุโลก',
        arriveTime: '17:55',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '202',
        trainType: 'ธรรมดา',
        departureStation: 'พิษณุโลก',
        departureTime: '06:05',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '14:05',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '207',
        trainType: 'ธรรมดา',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '14:10',
        arriveStation: 'นครสวรรค์',
        arriveTime: '19:35',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '208',
        trainType: 'ธรรมดา',
        departureStation: 'นครสวรรค์',
        departureTime: '05:00',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '10:15',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '209',
        trainType: 'ธรรมดา',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '11:20',
        arriveStation: 'บ้านตาคลี',
        arriveTime: '15:40',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '210',
        trainType: 'ธรรมดา',
        departureStation: 'บ้านตาคลี',
        departureTime: '16:00',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '20:35',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '211',
        trainType: 'ธรรมดา',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '12:55',
        arriveStation: 'ตะพานหิน',
        arriveTime: '19:15',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '212',
        trainType: 'ธรรมดา',
        departureStation: 'ตะพานหิน',
        departureTime: '05:30',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '12:10',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '301',
        trainType: 'ชานเมือง',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '16:30',
        arriveStation: 'ลพบุรี',
        arriveTime: '19:40',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '302',
        trainType: 'ชานเมือง',
        departureStation: 'ลพบุรี',
        departureTime: '04:30',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '07:35',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '303',
        trainType: 'ชานเมือง',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '04:30',
        arriveStation: 'ลพบุรี',
        arriveTime: '07:05',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '304',
        trainType: 'ชานเมือง',
        departureStation: 'ลพบุรี',
        departureTime: '08:00',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '10:35',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '313',
        trainType: 'ชานเมือง',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '18:20',
        arriveStation: 'ชุมทางบ้านภาชี',
        arriveTime: '20:45',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '314',
        trainType: 'ชานเมือง',
        departureStation: 'ชุมทางบ้านภาชี',
        departureTime: '04:45',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '06:50',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '317',
        trainType: 'ชานเมือง',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '17:30',
        arriveStation: 'ลพบุรี',
        arriveTime: '20:20',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '318',
        trainType: 'ชานเมือง',
        departureStation: 'ลพบุรี',
        departureTime: '06:00',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '08:50',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '401',
        trainType: 'ท้องถิ่น',
        departureStation: 'ลพบุรี',
        departureTime: '06:00',
        arriveStation: 'พิษณุโลก',
        arriveTime: '10:55',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '402',
        trainType: 'ท้องถิ่น',
        departureStation: 'พิษณุโลก',
        departureTime: '13:45',
        arriveStation: 'ลพบุรี',
        arriveTime: '18:45',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '403',
        trainType: 'ท้องถิ่น',
        departureStation: 'พิษณุโลก',
        departureTime: '05:55',
        arriveStation: 'ศิลาอาสน์',
        arriveTime: '07:40',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '410',
        trainType: 'ท้องถิ่น',
        departureStation: 'ศิลาอาสน์',
        departureTime: '16:30',
        arriveStation: 'พิษณุโลก',
        arriveTime: '18:10',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '407',
        trainType: 'ท้องถิ่น',
        departureStation: 'นครสวรรค์',
        departureTime: '05:00',
        arriveStation: 'เชียงใหม่',
        arriveTime: '14:35',
        line: 'North',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '408',
        trainType: 'ท้องถิ่น',
        departureStation: 'เชียงใหม่',
        departureTime: '09:30',
        arriveStation: 'นครสวรรค์',
        arriveTime: '19:55',
        line: 'North',
        seats: [],
        desinations: []),
  ],
  [
    //รายชื่อสถานีที่ขบวนที่ระบุจอด พร้อมเวลา
    TrainList(
        trainNo: '21',
        trainType: 'ด่วนพิเศษดีเซลราง',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '06:15',
        arriveStation: 'อุบลราชธานี',
        arriveTime: '14:00',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '22',
        trainType: 'ด่วนพิเศษดีเซลราง',
        departureStation: 'อุบลราชธานี',
        departureTime: '14:50',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '22:35',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '23',
        trainType: 'ด่วนพิเศษ CNR',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '21:05',
        arriveStation: 'อุบลราชธานี',
        arriveTime: '16:35',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '24',
        trainType: 'ด่วนพิเศษ CNR',
        departureStation: 'อุบลราชธานี',
        departureTime: '19:00',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '04:50',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '25',
        trainType: 'ด่วนพิเศษ CNR',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '20:25',
        arriveStation: 'อุบลราชธานี',
        arriveTime: '06:25',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '26',
        trainType: 'ด่วนพิเศษ CNR',
        departureStation: 'อุบลราชธานี',
        departureTime: '19:40',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '05:50',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '71',
        trainType: 'ด่วน',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '10:35',
        arriveStation: 'อุบลราชธานี',
        arriveTime: '19:50',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '72',
        trainType: 'ด่วน',
        departureStation: 'อุบลราชธานี',
        departureTime: '05:40',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '14:30',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '75',
        trainType: 'ด่วน',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '08:45',
        arriveStation: 'หนองคาย',
        arriveTime: '17:30',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '76',
        trainType: 'ด่วน',
        departureStation: 'หนองคาย',
        departureTime: '07:45',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '16:35',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '133',
        trainType: 'เร็ว',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '21:25',
        arriveStation: 'หนองคาย',
        arriveTime: '07:55',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '134',
        trainType: 'เร็ว',
        departureStation: 'หนองคาย',
        departureTime: '18:50',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '05:30',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '135',
        trainType: 'เร็ว',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '07:10',
        arriveStation: 'อุบลราชธานี',
        arriveTime: '18:00',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '136',
        trainType: 'เร็ว',
        departureStation: 'อุบลราชธานี',
        departureTime: '07:00',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '17:55',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '139',
        trainType: 'เร็ว',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '19:25',
        arriveStation: 'อุบลราชธานี',
        arriveTime: '06:15',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '140',
        trainType: 'เร็ว',
        departureStation: 'อุบลราชธานี',
        departureTime: '20:30',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '07:10',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '141',
        trainType: 'เร็ว',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '23:05',
        arriveStation: 'อุบลราชธานี',
        arriveTime: '10:20',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '142',
        trainType: 'เร็ว',
        departureStation: 'อุบลราชธานี',
        departureTime: '17:35',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '04:10',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '233',
        trainType: 'ธรรมดา',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '11:40',
        arriveStation: 'สุรินทร์',
        arriveTime: '20:00',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '234',
        trainType: 'ธรรมดา',
        departureStation: 'สุรินทร์',
        departureTime: '05:20',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '14:15',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '339',
        trainType: 'ชานเมือง',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '05:20',
        arriveStation: 'ชุมทางแก่งคอย',
        arriveTime: '08:05',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '340',
        trainType: 'ชานเมือง',
        departureStation: 'ชุมทางแก่งคอย',
        departureTime: '08:45',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '11:10',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '341',
        trainType: 'ชานเมือง',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '17:00',
        arriveStation: 'ชุมทางแก่งคอย',
        arriveTime: '20:00',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '342',
        trainType: 'ชานเมือง',
        departureStation: 'ชุมทางแก่งคอย',
        departureTime: '05:30',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '08:30',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '415',
        trainType: 'ท้องถิ่น',
        departureStation: 'นครราชสีมา',
        departureTime: '06:20',
        arriveStation: 'หนองคาย',
        arriveTime: '12:05',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '418',
        trainType: 'ท้องถิ่น',
        departureStation: 'หนองคาย',
        departureTime: '12:55',
        arriveStation: 'นครราชสีมา',
        arriveTime: '18:35',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '417',
        trainType: 'ท้องถิ่น',
        departureStation: 'นครราชสีมา',
        departureTime: '15:55',
        arriveStation: 'อุดรธานี',
        arriveTime: '21:00',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '416',
        trainType: 'ท้องถิ่น',
        departureStation: 'อุดรธานี',
        departureTime: '05:55',
        arriveStation: 'นครราชสีมา',
        arriveTime: '10:55',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '419',
        trainType: 'ท้องถิ่น',
        departureStation: 'นครราชสีมา',
        departureTime: '11:15',
        arriveStation: 'อุบลราชธานี',
        arriveTime: '16:45',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '420',
        trainType: 'ท้องถิ่น',
        departureStation: 'อุบลราชธานี',
        departureTime: '18:10',
        arriveStation: 'ลำชี',
        arriveTime: '21:10',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '421',
        trainType: 'ท้องถิ่น',
        departureStation: 'นครราชสีมา',
        departureTime: '06:10',
        arriveStation: 'อุบลราชธานี',
        arriveTime: '12:15',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '422',
        trainType: 'ท้องถิ่น',
        departureStation: 'อุบลราชธานี',
        departureTime: '15:15',
        arriveStation: 'ลำชี',
        arriveTime: '18:15',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '423',
        trainType: 'ท้องถิ่น',
        departureStation: 'ลำชึ',
        departureTime: '04:40',
        arriveStation: 'สำโรงทาบ',
        arriveTime: '05:40',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '424',
        trainType: 'ท้องถิ่น',
        departureStation: 'สำโรงทาบ',
        departureTime: '05:50',
        arriveStation: 'นครราชสีมา',
        arriveTime: '09:50',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '425',
        trainType: 'ท้องถิ่น',
        departureStation: 'ลำชึ',
        departureTime: '05:30',
        arriveStation: 'อุบลราชธานี',
        arriveTime: '08:30',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '426',
        trainType: 'ท้องถิ่น',
        departureStation: 'อุบลราชธานี',
        departureTime: '12:30',
        arriveStation: 'นครราชสีมา',
        arriveTime: '18:25',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '427',
        trainType: 'ท้องถิ่น',
        departureStation: 'นครราชสีมา',
        departureTime: '14:20',
        arriveStation: 'อุบลราชธานี',
        arriveTime: '20:15',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '428',
        trainType: 'ท้องถิ่น',
        departureStation: 'อุบลราชธานี',
        departureTime: '06:20',
        arriveStation: 'นครราชสีมา',
        arriveTime: '11:45',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '429',
        trainType: 'ท้องถิ่น',
        departureStation: 'นครราชสีมา',
        departureTime: '17:55',
        arriveStation: 'ชุมทางบัวใหญ่',
        arriveTime: '19:25',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '430',
        trainType: 'ท้องถิ่น',
        departureStation: 'ชุมทางบัวใหญ่',
        departureTime: '05:50',
        arriveStation: 'นครราชสีมา',
        arriveTime: '07:20',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '431',
        trainType: 'ท้องถิ่น',
        departureStation: 'ชุมทางแก่งคอย',
        departureTime: '05:00',
        arriveStation: 'ขอนแก่น',
        arriveTime: '11:30',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '432',
        trainType: 'ท้องถิ่น',
        departureStation: 'ขอนแก่น',
        departureTime: '14:30',
        arriveStation: 'ชุมทางแก่งคอย',
        arriveTime: '20:30',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '433',
        trainType: 'ท้องถิ่น',
        departureStation: 'ชุมทางแก่งคอย',
        departureTime: '05:30',
        arriveStation: 'ชุมทางบัวใหญ่',
        arriveTime: '10:08',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '434',
        trainType: 'ท้องถิ่น',
        departureStation: 'ชุมทางบัวใหญ่',
        departureTime: '12:20',
        arriveStation: 'ชุมทางแก่งคอย',
        arriveTime: '17:10',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '437',
        trainType: 'ท้องถิ่น',
        departureStation: 'ชุมทางแก่งคอย',
        departureTime: '16:55',
        arriveStation: 'ลำนารายณ์',
        arriveTime: '18:26',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '438',
        trainType: 'ท้องถิ่น',
        departureStation: 'ลำนารายณ์',
        departureTime: '06:08',
        arriveStation: 'ชุมทางแก่งคอย',
        arriveTime: '07:40',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '439',
        trainType: 'ท้องถิ่น',
        departureStation: 'ชุมทางแก่งคอย',
        departureTime: '11:45',
        arriveStation: 'ชุมทางบัวใหญ่',
        arriveTime: '16:40',
        line: 'NorthEast',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '440',
        trainType: 'ท้องถิ่น',
        departureStation: 'ชุมทางบัวใหญ่',
        departureTime: '05:50',
        arriveStation: 'ชุมทางแก่งคอย',
        arriveTime: '10:40',
        line: 'NorthEast',
        seats: [],
        desinations: []),
  ],
  [
    //รายชื่อสถานีที่ขบวนที่ระบุจอด พร้อมเวลา
    TrainList(
        trainNo: '997',
        trainType: 'เร็ว',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '06:45',
        arriveStation: 'บ้านพลูตาหลวง',
        arriveTime: '09:50',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '998',
        trainType: 'เร็ว',
        departureStation: 'บ้านพลูตาหลวง',
        departureTime: '15:50',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '18:55',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '275',
        trainType: 'ธรรมดา',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '05:55',
        arriveStation: 'อรัญประเทศ',
        arriveTime: '11:11',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '276',
        trainType: 'ธรรมดา',
        departureStation: 'อรัญประเทศ',
        departureTime: '14:00',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '19:40',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '277',
        trainType: 'ธรรมดา',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '15:25',
        arriveStation: 'กบินทร์บุรี',
        arriveTime: '18:20',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '278',
        trainType: 'ธรรมดา',
        departureStation: 'กบินทร์บุรี',
        departureTime: '06:30',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '10:15',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '279',
        trainType: 'ธรรมดา',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '13:05',
        arriveStation: 'อรัญประเทศ',
        arriveTime: '17:21',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '280',
        trainType: 'ธรรมดา',
        departureStation: 'อรัญประเทศ',
        departureTime: '07:05',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '12:05',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '281',
        trainType: 'ธรรมดา',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '08:00',
        arriveStation: 'กบินทร์บุรี',
        arriveTime: '11:35',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '282',
        trainType: 'ธรรมดา',
        departureStation: 'กบินทร์บุรี',
        departureTime: '13:25',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '17:15',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '283',
        trainType: 'ธรรมดา',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '06:55',
        arriveStation: 'บ้านพลูตาหลวง',
        arriveTime: '11:20',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '284',
        trainType: 'ธรรมดา',
        departureStation: 'บ้านพลูตาหลวง',
        departureTime: '13:35',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '18:15',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '367',
        trainType: 'ชานเมือง',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '10:10',
        arriveStation: 'ชุมทางฉะเชิงเทรา',
        arriveTime: '11:45',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '368',
        trainType: 'ชานเมือง',
        departureStation: 'ชุมทางฉะเชิงเทรา',
        departureTime: '12:35',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '14:10',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '371',
        trainType: 'ชานเมือง',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '17:40',
        arriveStation: 'ปราจีนบุรี',
        arriveTime: '20:32',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '372',
        trainType: 'ชานเมือง',
        departureStation: 'ปราจีนบุรี',
        departureTime: '05:00',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '08:15',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '379',
        trainType: 'ชานเมือง',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '16:35',
        arriveStation: 'ชุมทางฉะเชิงเทรา',
        arriveTime: '18:05',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '380',
        trainType: 'ชานเมือง',
        departureStation: 'ชุมทางฉะเชิงเทรา',
        departureTime: '05:45',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '07:45',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '383',
        trainType: 'ชานเมือง',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '18:25',
        arriveStation: 'ชุมทางฉะเชิงเทรา',
        arriveTime: '20:00',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '384',
        trainType: 'ชานเมือง',
        departureStation: 'ชุมทางฉะเชิงเทรา',
        departureTime: '05:20',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '07:10',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '389',
        trainType: 'ชานเมือง',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '12:10',
        arriveStation: 'ชุมทางฉะเชิงเทรา',
        arriveTime: '13:30',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '390',
        trainType: 'ชานเมือง',
        departureStation: 'ชุมทางฉะเชิงเทรา',
        departureTime: '14:05',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '15:25',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '391',
        trainType: 'ชานเมือง',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '16:55',
        arriveStation: 'ชุมทางฉะเชิงเทรา',
        arriveTime: '18:25',
        line: 'East',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '388',
        trainType: 'ชานเมือง',
        departureStation: 'ชุมทางฉะเชิงเทรา',
        departureTime: '07:05',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '08:35',
        line: 'East',
        seats: [],
        desinations: []),
  ],
  [
    //รายชื่อสถานีที่ขบวนที่ระบุจอด พร้อมเวลา
    TrainList(
        trainNo: '31',
        trainType: 'ด่วนพิเศษ CNR',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '14:50',
        arriveStation: 'ชุมทางหาดใหญ่',
        arriveTime: '07:25',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '32',
        trainType: 'ด่วนพิเศษ CNR',
        departureStation: 'ชุมทางหาดใหญ่',
        departureTime: '17:45',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '10:50',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '37',
        trainType: 'ด่วนพิเศษ',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '15:35',
        arriveStation: 'สุไหงโก-ลก',
        arriveTime: '12:30',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '38',
        trainType: 'ด่วนพิเศษ',
        departureStation: 'สุไหงโก-ลก',
        departureTime: '14:20',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '12:05',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '39',
        trainType: 'ด่วนพิเศษดีเซลราง',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '22:20',
        arriveStation: 'สุราษฎร์ธานี',
        arriveTime: '09:25',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '40',
        trainType: 'ด่วนพิเศษดีเซลราง',
        departureStation: 'สุราษฎร์ธานี',
        departureTime: '10:40',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '20:30',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '43',
        trainType: 'ด่วนพิเศษดีเซลราง',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '08:10',
        arriveStation: 'สุราษฎร์ธานี',
        arriveTime: '18:50',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '44',
        trainType: 'ด่วนพิเศษดีเซลราง',
        departureStation: 'สุราษฎร์ธานี',
        departureTime: '21:05',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '08:45',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '45',
        trainType: 'ด่วนพิเศษ',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '15:35',
        arriveStation: 'ปาดังเบซาร์',
        arriveTime: '09:50',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '46',
        trainType: 'ด่วนพิเศษ',
        departureStation: 'ปาดังเบซาร์',
        departureTime: '17:00',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '12:05',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '83',
        trainType: 'ด่วน',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '17:30',
        arriveStation: 'ตรัง',
        arriveTime: '08:50',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '84',
        trainType: 'ด่วน',
        departureStation: 'ตรัง',
        departureTime: '17:00',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '09:25',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '85',
        trainType: 'ด่วน',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '20:10',
        arriveStation: 'นครศรีธรรมราช',
        arriveTime: '12:05',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '86',
        trainType: 'ด่วน',
        departureStation: 'นครศรีธรรมราช',
        departureTime: '15:20',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '07:45',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '167',
        trainType: 'เร็ว',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '18:50',
        arriveStation: 'กันตัง',
        arriveTime: '12:05',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '168',
        trainType: 'เร็ว',
        departureStation: 'กันตัง',
        departureTime: '12:55',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '07:00',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '169',
        trainType: 'เร็ว',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '16:10',
        arriveStation: 'ยะลา',
        arriveTime: '11:45',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '170',
        trainType: 'เร็ว',
        departureStation: 'ยะลา',
        departureTime: '12:35',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '08:25',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '171',
        trainType: 'เร็ว',
        departureStation: 'กรุงเทพอภิวัฒน์',
        departureTime: '13:10',
        arriveStation: 'สุไหงโก-ลก',
        arriveTime: '10:50',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '172',
        trainType: 'เร็ว',
        departureStation: 'สุไหงโก-ลก',
        departureTime: '12:00',
        arriveStation: 'กรุงเทพอภิวัฒน์',
        arriveTime: '10:30',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '251',
        trainType: 'ธรรมดา',
        departureStation: 'ธนบุรี',
        departureTime: '13:10',
        arriveStation: 'ประจวบคีรีขันธ์',
        arriveTime: '20:00',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '252',
        trainType: 'ธรรมดา',
        departureStation: 'ประจวบคีรีขันธ์',
        departureTime: '04:50',
        arriveStation: 'ธนบุรี',
        arriveTime: '11:45',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '255',
        trainType: 'ธรรมดา',
        departureStation: 'ธนบุรี',
        departureTime: '07:30',
        arriveStation: 'หลังสวน',
        arriveTime: '20:20',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '254',
        trainType: 'ธรรมดา',
        departureStation: 'หลังสวน',
        departureTime: '06:20',
        arriveStation: 'ธนบุรี',
        arriveTime: '18:30',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '257',
        trainType: 'ธรรมดา',
        departureStation: 'ธนบุรี',
        departureTime: '07:45',
        arriveStation: 'นํ้าตก',
        arriveTime: '12:35',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '258',
        trainType: 'ธรรมดา',
        departureStation: 'นํ้าตก',
        departureTime: '12:55',
        arriveStation: 'ธนบุรี',
        arriveTime: '17:40',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '259',
        trainType: 'ธรรมดา',
        departureStation: 'ธนบุรี',
        departureTime: '07:45',
        arriveStation: 'นํ้าตก',
        arriveTime: '12:35',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '260',
        trainType: 'ธรรมดา',
        departureStation: 'นํ้าตก',
        departureTime: '05:20',
        arriveStation: 'ธนบุรี',
        arriveTime: '09:45',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '261',
        trainType: 'ธรรมดา',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '09:20',
        arriveStation: 'หัวหิน',
        arriveTime: '14:15',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '262',
        trainType: 'ธรรมดา',
        departureStation: 'หัวหิน',
        departureTime: '14:30',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '20:20',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '351',
        trainType: 'ชานเมือง',
        departureStation: 'ธนบุรี',
        departureTime: '18:25',
        arriveStation: 'ราชบุรี',
        arriveTime: '20:35',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '352',
        trainType: 'ชานเมือง',
        departureStation: 'ราชบุรี',
        departureTime: '04:45',
        arriveStation: 'ธนบุรี',
        arriveTime: '07:10',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '355',
        trainType: 'ชานเมือง',
        departureStation: 'กรุงเทพ (หัวลำโพง)',
        departureTime: '16:40',
        arriveStation: 'สุพรรณบุรี',
        arriveTime: '20:05',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '356',
        trainType: 'ชานเมือง',
        departureStation: 'สุพรรณบุรี',
        departureTime: '04:00',
        arriveStation: 'กรุงเทพ (หัวลำโพง)',
        arriveTime: '08:05',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '445',
        trainType: 'ท้องถิ่น',
        departureStation: 'ชุมพร',
        departureTime: '06:15',
        arriveStation: 'ชุมทางหาดใหญ่',
        arriveTime: '17:00',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '446',
        trainType: 'ท้องถิ่น',
        departureStation: 'ชุมทางหาดใหญ่',
        departureTime: '06:35',
        arriveStation: 'ชุมพร',
        arriveTime: '17:05',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '447',
        trainType: 'ท้องถิ่น',
        departureStation: 'สุราษฎร์ธานี',
        departureTime: '06:20',
        arriveStation: 'สุไหงโกลก',
        arriveTime: '17:40',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '448',
        trainType: 'ท้องถิ่น',
        departureStation: 'สุไหงโกลก',
        departureTime: '06:30',
        arriveStation: 'สุราษฎร์ธานี',
        arriveTime: '17:55',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '451',
        trainType: 'ท้องถิ่น',
        departureStation: 'นครศรีธรรมราช',
        departureTime: '06:00',
        arriveStation: 'สุไหงโกลก',
        arriveTime: '14:45',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '452',
        trainType: 'ท้องถิ่น',
        departureStation: 'สุไหงโกลก',
        departureTime: '09:00',
        arriveStation: 'นครศรีธรรมราช',
        arriveTime: '17:50',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '453',
        trainType: 'ท้องถิ่น',
        departureStation: 'ยะลา',
        departureTime: '06:30',
        arriveStation: 'สุไหงโกลก',
        arriveTime: '08:40',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '454',
        trainType: 'ท้องถิ่น',
        departureStation: 'สุไหงโกลก',
        departureTime: '15:25',
        arriveStation: 'ยะลา',
        arriveTime: '17:35',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '455',
        trainType: 'ท้องถิ่น',
        departureStation: 'นครศรีธรรมราช',
        departureTime: '09:50',
        arriveStation: 'ยะลา',
        arriveTime: '16:30',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '456',
        trainType: 'ท้องถิ่น',
        departureStation: 'ยะลา',
        departureTime: '06:35',
        arriveStation: 'นครศรีธรรมราช',
        arriveTime: '13:40',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '463',
        trainType: 'ท้องถิ่น',
        departureStation: 'พัทลุง',
        departureTime: '06:25',
        arriveStation: 'สุไหงโกลก',
        arriveTime: '12:45',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '464',
        trainType: 'ท้องถิ่น',
        departureStation: 'สุไหงโกลก',
        departureTime: '12:55',
        arriveStation: 'พัทลุง',
        arriveTime: '18:25',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '485',
        trainType: 'ท้องถิ่น',
        departureStation: 'กาญจนบุรี',
        departureTime: '06:08',
        arriveStation: 'นํ้าตก',
        arriveTime: '08:20',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '486',
        trainType: 'ท้องถิ่น',
        departureStation: 'นํ้าตก',
        departureTime: '15:30',
        arriveStation: 'กาญจนบุรี',
        arriveTime: '17:33',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '489',
        trainType: 'ท้องถิ่น',
        departureStation: 'สุราษฎร์ธานี',
        departureTime: '16:55',
        arriveStation: 'คีรีรัฐนิคม',
        arriveTime: '17:40',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '490',
        trainType: 'ท้องถิ่น',
        departureStation: 'คีรีรัฐนิคม',
        departureTime: '06:15',
        arriveStation: 'สุราษฎร์ธานี',
        arriveTime: '07:00',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '947',
        trainType: 'ด่วนพิเศษ',
        departureStation: 'ชุมทางหาดใหญ่',
        departureTime: '07:40',
        arriveStation: 'ปาดังเบซาร์',
        arriveTime: '08:35',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '948',
        trainType: 'ด่วนพิเศษ',
        departureStation: 'ปาดังเบซาร์',
        departureTime: '08:55',
        arriveStation: 'ชุมทางหาดใหญ่',
        arriveTime: '09:50',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '949',
        trainType: 'ด่วนพิเศษ',
        departureStation: 'ชุมทางหาดใหญ่',
        departureTime: '14:00',
        arriveStation: 'ปาดังเบซาร์',
        arriveTime: '14:55',
        line: 'South',
        seats: [],
        desinations: []),
    TrainList(
        trainNo: '950',
        trainType: 'ด่วนพิเศษ',
        departureStation: 'ปาดังเบซาร์',
        departureTime: '15:40',
        arriveStation: 'ชุมทางหาดใหญ่',
        arriveTime: '16:35',
        line: 'South',
        seats: [],
        desinations: []),
  ]
];
